server:
  port: 9001
      
spring:
  application:
    name: student-service
  cloud:
    config:
      uri: http://localhost:8888
      
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream