server:
  port: 9001
      
spring:
  application:
    name: student-service
  boot:
    admin:
      client:
        url:
        - http://localhost:7700
      
management:
  endpoints:
    web:
      exposure:
        include: "*"